### ISSUE TITLE
Failed to execute 'querySelector' on 'Document': '.workspace.' is not a valid selector

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/GoogleSignIn#6] opened 2015-05-14 20:03 UTC
On sign in or sign out the next exception happens:

```
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '.workspace.' is not a valid selector.
juicy-display-router.html:27
```

JSON patch:
```json
[
{
    "op": "replace",
    "path": "/_ver#s",
    "value": 1
},
{
    "op": "test",
    "path": "/_ver#c$",
    "value": 0
},
{
    "op": "replace",
    "path": "/user/GoogleSignIn/IsSignedIn",
    "value": true
},
{
    "op": "replace",
    "path": "/user/GoogleSignIn/User/Username",
    "value": "106669544181213700915"
},
{
    "op": "replace",
    "path": "/user/GoogleSignIn/WhoIs/Name",
    "value": "Konstantin Mi"
},
{
    "op": "replace",
    "path": "/user/GoogleSignIn/WhoIs/ImageURL",
    "value": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
},
{
    "op": "replace",
    "path": "/user/GoogleSignIn/GooglePerson/Link",
    "value": "https://plus.google.com/106669544181213700915"
},
{
    "op": "replace",
    "path": "/user/GoogleSignIn/GooglePerson/Picture",
    "value": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
},
{
    "op": "add",
    "path": "/workspaces/0",
    "value": {
        "Launcher": {
            "Html": null,
            "appName": "googlesignin",
            "_juicyTilesSetup": null,
            "_partialId": "",
            "_editorOpened": false
        },
        "GoogleSignIn": {
        },
        "Html": ""
    }
}
]
```

**Comment by warpech** [comment] 2015-05-20 11:53
Confirmed. Also happens in SignIn

**Comment by warpech** [comment] 2015-05-20 12:16
Happens because signing in/out creates a workspace in Launcher (which it shouldn't). 

The actual error is because the workspace does not contain `AppName` (which it should).

There should be:

1. a better error message in `juicy-display-router`
2. always an `AppName` in workspaces
3. no workspace for SignIn/GoogleSignIn unless explicitly created

**Comment by miyconst** [comment] 2015-05-20 15:00
I don't think this is a client side issue, @warpech who is responsible for this issue?

**Comment by miyconst** [comment] 2015-06-01 16:05
1. Done.

**Comment by warpech** [comment] 2015-06-05 08:40
Thanks. I will investigate 2. and 3.

**Comment by warpech** [comment] 2015-06-05 13:08
Pushed a fix for point 2. @tomalec can you review it? https://github.com/Polyjuice/Launcher/compare/workspace-fix

**Comment by tomalec** [comment] 2015-06-05 17:59
As app name is now part of _partial identifier_ so it's no longer needed to identify a partial in browser, we can remove it. It will be still used in serialize internally, to fetch `partialId`.

**Comment by warpech** [comment] 2015-09-02 11:57
Bump

The error message `Failed to execute 'querySelector' on 'Document': '.workspace.' is not a valid selector` still appears in GoogleSignIn + Launcher. @miyconst knows how to reproduce it

**Comment by warpech** [comment] 2016-03-23 18:25
Point 2. is now done in Starcounter (https://github.com/Starcounter/Starcounter/issues/2902) and being further improved in Launcher (https://github.com/StarcounterPrefabs/Launcher/issues/208)

**Comment by warpech** [comment] 2016-03-24 14:29
The remaining, point 3 is now tracked in a separate issue: https://github.com/StarcounterSamples/GoogleSignIn/issues/8

**Closed by warpech** 2016-03-24 14:29 UTC
